name: Manually trigger an Azure Machine Learning job

on: [push]

jobs:
  variables:
  - name: RESOURCEGRP
    value: rg-mltest
  - name: WORKSPACE
    value: amlw-workspace-test
  - name: FILEPATH
    value: src/job.yml

  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file ${{ variables.FILEPATH }} --resource-group ${{ variables.RESOURCEGRP }} --workspace-name ${{ variables.WORKSPACE }}


