name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        $resourceGroup = "rg-mltest"
        $workspace = "amlw-workspace-test"
        $filepath = 'src/job.yml'
        az ml job create --file $filepath --resource-group $resourceGroup --workspace-name $workspace


