name: On merge to main run an Azure Machine Learning job

on:
  push:
    branches:
      - main
jobs:
  experiment:
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file 'src/job-test.yml' --resource-group 'rg-mltest' --workspace-name 'amlw-workspace-test'
  production:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file 'src/job-prod.yml' --resource-group 'rg-ml-prod' --workspace-name 'amlw-workspace-prod'
    - name: Register and deploy model
      run: |
        az ml model create --name 'azml-model-prod' --version 1 --path 'azureml://jobs/azmlexperimentjob/outputs/artifacts/paths/model/' --resource-group 'rg-ml-prod' --workspace-name 'amlw-workspace-prod'


